name: CI Deploy to GitHub Pages and Keep dist on main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 或者你使用的其他版本

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: 'Auto deploy from main'

      - name: Commit and push dist to main branch
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "chore: update dist on main" || echo "No changes to commit"
          git push origin main
